# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2lIxKO50QyUOSa40bEGT0EXBMIfwVvu
"""

from setuptools import setup, find_packages

setup(
    name="keyword_summarizer",            # Name of your package
    version="0.1.0",                      # Package version
    description="Summarize text with KeyBERT-based keyword injection and fine-tuned BART models",
    author="ValeXpoli",
    author_email="valerioxefteris.vx@gmail.com",
    url="https://github.com/ValeXpoli/keyword_summarizer",  # or any repo URL
    packages=find_packages(),
    python_requires=">=3.7",
    install_requires=[
        "torch>=1.9.0",
        "transformers>=4.0.0",
        "sentence-transformers>=2.2.2",
        "keybert>=0.7.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
)
